# Generated by Django 3.1.1 on 2020-09-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200915_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='images',
        ),
        migrations.AddField(
            model_name='listing',
            name='image1',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='listing',
            name='image2',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='listing',
            name='image3',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='listing',
            name='image4',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.FloatField(),
        ),
    ]
