# Generated by Django 3.1.1 on 2020-09-17 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_listing_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image4',
        ),
    ]
