# Generated by Django 3.1.1 on 2020-09-17 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200915_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='region',
            new_name='county',
        ),
    ]
